# MLP Model Configuration

# Data paths
data_paths:
  raw: "data/raw/casos_cadera.xlsx"
  processed: "data/processed/modified_base.xlsx"
  preprocessed: "data/preprocessed"
  results: "data/results"
  models: "data/models"

# Model hyperparameters
model_params:
  hidden_layer_sizes:
    - [32, 16]
    - [64, 32]
    - [16, 8]
  alpha:
    - 0.0001           # L2 regularization (weight decay)
    - 0.00001
  learning_rate_init:
    - 0.001
    - 0.0005
  max_iter:
    - 300              # Reduce iteraciones para early stopping efectivo
    - 500
  early_stopping: true
  random_state: 42

# Output configuration
output:
  results_file: "mlp_results.csv"
  output_file: "data/results_comparativa.xlsx"